package com.org.example.PCShopApp;

import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.FlatLaf;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author PC
 */
public class ConsumerInterface extends javax.swing.JFrame {

    /**
     * Creates new form ConsumerInterface
     */
    public ConsumerInterface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        CBCPU = new javax.swing.JComboBox<>();
        CBCPU1 = new javax.swing.JComboBox<>();
        CBCPU2 = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        TFFirstN = new javax.swing.JTextField();
        TFLastN = new javax.swing.JTextField();
        TFEmail = new javax.swing.JTextField();
        TFAdress = new javax.swing.JTextField();
        TFCity = new javax.swing.JTextField();
        TFProvince = new javax.swing.JTextField();
        BTBuild = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TAPartsTotal = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PCBuilder");
        setForeground(java.awt.Color.darkGray);
        setPreferredSize(new java.awt.Dimension(1440, 1080));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(45, 48, 85));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setPreferredSize(new java.awt.Dimension(1440, 1024));

        jTabbedPane1.setBackground(new java.awt.Color(40, 53, 98));

        jPanel2.setFocusable(false);
        jPanel2.setName(""); // NOI18N
        jPanel2.setPreferredSize(new java.awt.Dimension(1400, 860));
        jPanel2.setRequestFocusEnabled(false);

        CBCPU.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        CBCPU.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "none", "" }));
        CBCPU.setPreferredSize(new java.awt.Dimension(311, 44));
        CBCPU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBCPUActionPerformed(evt);
            }
        });

        CBCPU1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        CBCPU1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "none", "" }));
        CBCPU1.setPreferredSize(new java.awt.Dimension(311, 44));
        CBCPU1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBCPU1ActionPerformed(evt);
            }
        });

        CBCPU2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        CBCPU2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "none", "" }));
        CBCPU2.setPreferredSize(new java.awt.Dimension(311, 44));
        CBCPU2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBCPU2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(CBCPU, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CBCPU1, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CBCPU2, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(215, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CBCPU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CBCPU1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CBCPU2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(760, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Components", jPanel2);

        jPanel3.setBackground(new java.awt.Color(26, 43, 59));
        jPanel3.setPreferredSize(new java.awt.Dimension(1400, 860));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Peripherals", jPanel3);

        TFFirstN.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        TFFirstN.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        TFFirstN.setText("Full Name");
        TFFirstN.setToolTipText("");
        TFFirstN.setPreferredSize(new java.awt.Dimension(230, 40));
        TFFirstN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFFirstNActionPerformed(evt);
            }
        });

        TFLastN.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        TFLastN.setText("#");
        TFLastN.setPreferredSize(new java.awt.Dimension(230, 40));

        TFEmail.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        TFEmail.setText("Email");
        TFEmail.setPreferredSize(new java.awt.Dimension(230, 40));

        TFAdress.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        TFAdress.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        TFAdress.setText("Addres");
        TFAdress.setToolTipText("");
        TFAdress.setPreferredSize(new java.awt.Dimension(230, 40));
        TFAdress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFAdressActionPerformed(evt);
            }
        });

        TFCity.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        TFCity.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        TFCity.setText("City");
        TFCity.setToolTipText("");
        TFCity.setPreferredSize(new java.awt.Dimension(230, 40));
        TFCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFCityActionPerformed(evt);
            }
        });

        TFProvince.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        TFProvince.setText("Province");
        TFProvince.setPreferredSize(new java.awt.Dimension(230, 40));
        TFProvince.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFProvinceActionPerformed(evt);
            }
        });

        BTBuild.setBackground(new java.awt.Color(25, 36, 57));
        BTBuild.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BTBuild.setText("Finalize Build");
        BTBuild.setToolTipText("Prepairs List of your build and sent to system");
        BTBuild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTBuildActionPerformed(evt);
            }
        });

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setToolTipText("Price");
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        TAPartsTotal.setEditable(false);
        TAPartsTotal.setColumns(20);
        TAPartsTotal.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        TAPartsTotal.setLineWrap(true);
        TAPartsTotal.setRows(1);
        TAPartsTotal.setTabSize(1);
        TAPartsTotal.setFocusable(false);
        jScrollPane1.setViewportView(TAPartsTotal);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TFAdress, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TFFirstN, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TFLastN, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TFCity, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TFEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TFProvince, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BTBuild))))
                .addGap(15, 15, 15))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {TFAdress, TFCity, TFEmail, TFFirstN, TFLastN, TFProvince});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BTBuild))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TFFirstN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TFEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TFLastN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TFAdress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TFCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TFProvince, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(42, 42, 42)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 860, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Computer Parts");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TFFirstNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFFirstNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFFirstNActionPerformed

    private void TFAdressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFAdressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFAdressActionPerformed

    private void TFCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFCityActionPerformed

    private void TFProvinceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFProvinceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFProvinceActionPerformed

    private void BTBuildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTBuildActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTBuildActionPerformed

    private void CBCPUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBCPUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBCPUActionPerformed

    private void CBCPU1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBCPU1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBCPU1ActionPerformed

    private void CBCPU2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBCPU2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBCPU2ActionPerformed

    public static void main(String args[]) {
        FlatDarkLaf.setup();
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ConsumerInterface frame = new ConsumerInterface();
                //frame.setExtendedState(JFrame.MAXIMIZED_BOTH); // fills screen, includes taskbar
                frame.setVisible(true);
                //frame.setResizable(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTBuild;
    private javax.swing.JComboBox<String> CBCPU;
    private javax.swing.JComboBox<String> CBCPU1;
    private javax.swing.JComboBox<String> CBCPU2;
    private javax.swing.JTextArea TAPartsTotal;
    private javax.swing.JTextField TFAdress;
    private javax.swing.JTextField TFCity;
    private javax.swing.JTextField TFEmail;
    private javax.swing.JTextField TFFirstN;
    private javax.swing.JTextField TFLastN;
    private javax.swing.JTextField TFProvince;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
